title: Tramcrazy's Blog
description: A blog about cybersecurity, coding, technology and more!
author: tramcrazy
github: https://github.com/tramcrazy
about: I'm a cybersecurity and programming enthusiast based in the UK, who loves writing about and filming projects.
disqus_shortname:
google_analytics: G-BQWRJ839GV

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/tramcrazy"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://tramcrazy.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
